<?php

namespace JayAnta\AiGuard\Console\Commands;

use Illuminate\Console\Command;
use JayAnta\AiGuard\Services\BotSignatures;

class AiGuardRobotsTxt extends Command
{
    protected $signature = 'ai-guard:robots-txt
        {--output= : Write to file path (default: print to console)}
        {--categories=ai_training,ai_assistants : Comma-separated categories to block}
        {--all : Block all categories except search_engines}
        {--append : Append to existing robots.txt instead of overwriting}';

    protected $description = 'Generate a robots.txt that blocks AI crawlers and scrapers';

    public function handle(): int
    {
        $categories = $this->getSelectedCategories();
        $allBots = BotSignatures::getCategories();
        $lines = [];

        $lines[] = '# ============================================================';
        $lines[] = '# AI Guard — robots.txt';
        $lines[] = '# Generated by jayanta/laravel-ai-guard';
        $lines[] = '# https://github.com/jay123anta/laravel-ai-guard';
        $lines[] = '# ============================================================';
        $lines[] = '';

        $totalBots = 0;

        foreach ($categories as $categoryKey) {
            if (!isset($allBots[$categoryKey])) {
                continue;
            }

            $category = $allBots[$categoryKey];
            $lines[] = '# ' . str_repeat('-', 60);
            $lines[] = '# ' . $category['label'] . ' (' . count($category['bots']) . ' bots)';
            $lines[] = '# ' . str_repeat('-', 60);

            foreach ($category['bots'] as $bot) {
                // Clean bot name for robots.txt — remove trailing slashes and special chars
                $botName = rtrim($bot, '/ -');
                if ($botName === '') {
                    continue;
                }

                $lines[] = 'User-agent: ' . $botName;
                $lines[] = 'Disallow: /';
                $lines[] = '';
                $totalBots++;
            }
        }

        // Add a catch-all section for known patterns
        $lines[] = '# ' . str_repeat('-', 60);
        $lines[] = '# Allow search engines (don\'t block these)';
        $lines[] = '# ' . str_repeat('-', 60);
        $lines[] = 'User-agent: Googlebot';
        $lines[] = 'Allow: /';
        $lines[] = '';
        $lines[] = 'User-agent: Bingbot';
        $lines[] = 'Allow: /';
        $lines[] = '';
        $lines[] = 'User-agent: *';
        $lines[] = 'Allow: /';
        $lines[] = '';
        $lines[] = '# Generated: ' . now()->toDateTimeString();
        $lines[] = '# Bots blocked: ' . $totalBots;
        $lines[] = '# Categories: ' . implode(', ', $categories);

        $content = implode("\n", $lines) . "\n";

        // Output
        $outputPath = $this->option('output');

        if ($outputPath === null) {
            // Print to console
            $this->line('');
            $this->line($content);
            $this->line('');
            $this->info("Generated robots.txt with {$totalBots} blocked bots.");
            $this->line('');
            $this->line('To save to public/robots.txt:');
            $this->line('  php artisan ai-guard:robots-txt --output=public/robots.txt');

            return Command::SUCCESS;
        }

        // Resolve path
        $fullPath = base_path($outputPath);

        if ($this->option('append') && file_exists($fullPath)) {
            $existing = file_get_contents($fullPath);
            $content = $existing . "\n\n" . $content;
            file_put_contents($fullPath, $content);
            $this->info("Appended {$totalBots} bot rules to {$outputPath}");
        } else {
            if (file_exists($fullPath) && !$this->option('append')) {
                if (!$this->confirm("{$outputPath} already exists. Overwrite?")) {
                    $this->warn('Cancelled.');
                    return Command::SUCCESS;
                }
            }
            file_put_contents($fullPath, $content);
            $this->info("Written {$totalBots} bot rules to {$outputPath}");
        }

        return Command::SUCCESS;
    }

    private function getSelectedCategories(): array
    {
        if ($this->option('all')) {
            return ['ai_training', 'ai_assistants', 'seo_tools', 'scrapers', 'bad_bots', 'data_harvesters'];
        }

        $input = $this->option('categories');
        $categories = array_map('trim', explode(',', $input));

        return array_filter($categories, fn ($c) => $c !== '');
    }
}
